baseURL: "https://geraldmokereke.xyz"
languageCode: "en-us"
title: "Gerald's Journal"
theme: "rocinante"
pagination:
  pagerSize: 8

markup:
  highlight:
    style: "monokailight"
  goldmark:
    renderer:
      unsafe: true

params:
  mainSections:
    - "posts"
    - "photos"
  email: "mail@example.com"
  favicon: "https://i.ibb.co/YNRSK0Z/gerald-logo.png"
  about: |
    I'm Gerald Maduabuchi Okereke. Welcome to my thoughts, my journal and my little space on the web. 

  links:
    - link:
        - name: "Github"
          href: "https://github.com/grayoj"
          new_tab: true
        - name: "X"
          href: "https://twitter.com/geraldmokereke"
          new_tab: true
        - name: "Email"
          href: "mailto:geraldmokereke@gmail.com"
          new_tab: true
